# unix server
# token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE4MjI5MzQ4MDAsImlzcyI6InVuaXgiLCJuYW1lIjoieHlwIiwibmJmIjoxNzUwOTM0ODAwLCJzdWIiOiJ4eXAiLCJ2aWRlbyI6eyJyb29tIjoibXktcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.F4_o9_N5gu-r2J5F1oRzPk2SNwFiw4-OJPH73Ltbspw"
# url: "https://stream.unixgroup.cn:8443"
# livekit server
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk5MzYyODYsImlzcyI6IkFQSXduZkVoTmNUY2ZzQSIsIm5iZiI6MTc1MDkzNjI4Niwic3ViIjoiejEiLCJ2aWRlbyI6eyJjYW5QdWJsaXNoIjp0cnVlLCJjYW5QdWJsaXNoRGF0YSI6dHJ1ZSwiY2FuU3Vic2NyaWJlIjp0cnVlLCJyb29tIjoibXktcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.4NZQOGMPEM6f6-pl4MriDYdmufK-LctP1mesMTQpPNo"
url: "wss://zwindz1-lam2j1uj.livekit.cloud"